### ISSUE TITLE
Site link to example.com in Netlify CMS

### ISSUE THREAD

**Issue by watershed** [andybelldesign/hylia#54]
First of all, Andy, thank you. Hylia is a wonderful resource.

I dipped a toe into its waters yesterday and have noticed that, when in Netlify CMS, the top right link goes to `example.com`. This is my first time exposure to Netlify CMS. I presume that the top right link is meant to be to the site being edited.

I don't think I've overlooked something in Netlify settings.

<img width="294" alt="netlify-cms_site-link" src="https://user-images.githubusercontent.com/219060/60584264-b4701900-9d84-11e9-96d9-8b2a0a7c578a.png">

**Comment by andybelldesign** [comment]
Hey @watershed! Thank you for the kind words. I've found [where that comes from](https://github.com/andybelldesign/hylia/blob/master/src/admin/config.yml#L5). The problem is that the front-end stores the site url in a [data file](https://github.com/andybelldesign/hylia/blob/master/src/_data/site.json#L5).

I should probably flag this as a documentation improvement opportunity 👍

**Comment by watershed** [comment]
Great. Thanks Andy 👍
