### ISSUE TITLE
Fix 2 severe security vulnerabilities please

### ISSUE THREAD

**Issue by shreeshbhat** [andybelldesign/hylia#70]
Solution : 
Kindly upgrade lodash to version 4.17.13 or later.
Upgrade bl to version 0.9.5 or later.

Also, I am seeing a bunch of vulnerabilities while doing npm install.
`found 238 vulnerabilities (2 moderate, 236 high)`
How to tackle this in the long run?
I am new to eleventy and static site generators.
However, I am open to helping with PRs if you can guide me.

**Comment by andreavaghi** [comment]
I've encountered this issue yesterday and i solved it in two steps.

For the one about `lodash`, i've managed to fix it automatically running `npm audit fix`.
For `bl` (and also `semver` in my case) the issue is related to a package that is used by NetlifyCMS that is included with Hylia, `rollup-plugin-node-builtins`. It doesn't seems to be maintained in the last two years, but [there is an open issue](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/issues/47) that suggests to use a [forked version](https://www.npmjs.com/package/@joseph184/rollup-plugin-node-builtins) to solve the problem.

Not an ideal solution (it would be better to use a maintained package) but it fixes those vulnerabilities alerts

**Comment by andybelldesign** [comment]
Ah interesting. Thanks @andreavaghi!

**Comment by andybelldesign** [comment]
Resolved with #72
